version: '3'

services:
  mysql_5:
    image: "mysql:5.7"
    platform: linux/amd64
    container_name: mysql_5
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: shop
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    volumes:
      - ./db:/var/lib/mysql
      - ./sql/initdb.d:/docker-entrypoint-initdb.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--lower_case_table_names=1"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - default_network

  application:
    container_name: application
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
    depends_on:
      - mysql_5
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_5:3306/shop?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    volumes:
      - ./build:/application
    restart: always
    networks:
      - default_network

networks:
  default_network: