
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafe?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
    secret:

logging:
    level:
        root: INFO
        com:
            payhere:
                shop: DEBUG